### ISSUE TITLE
Session is no longer valid with Lavalink

### ISSUE THREAD

**Issue by Diniboy1123** [napstr/Magma#18]
I just updated Lavalink to the latest version in its releases tab and now I could see this three times within a short period:

![Sentry page](https://user-images.githubusercontent.com/29148882/51803842-c4298580-2259-11e9-95f5-8f560c2c85c1.png)

Stack trace:

```
    at space.npstr.magma.connections.AudioWebSocket.handleWebSocketClosed(AudioWebSocket.java:263)
    at space.npstr.magma.connections.AudioWebSocket.hookOnNext(AudioWebSocket.java:169)
    at space.npstr.magma.connections.AudioWebSocket.hookOnNext(AudioWebSocket.java:74)
    at reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:158)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)
    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
```

What can I do?

**Comment by schnapster** [comment]
>I just updated Lavalink to the latest version

Hey there, the latest version of Lavalink no longer uses the Magma library, but a fork of it. I do not provide support for any forks of my projects.
